# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dba536ce62cce3ec128a5f7551b948f3f5ea0fd104bc16af220834286530c90db03e7ea99406d424c19ce505ee69257ba643f2239de37df3f1eb679ea190db4e

test:
  secret_key_base: f4a52f0acbb4208e9ff1278306d959e207a56298f74f39c1eb82ff3a4a320ad8f634c44bde32460533de0c66791c6951d082f211d5ba93ca1a7fbfce19aa2b38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
